In [1]:
import torch

In [2]:
#number 
t1= torch.tensor(4.)
t1

tensor(4.)

In [3]:
t1.dtype

torch.float32

In [4]:
#Vector
t2 = torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [5]:
t2.dtype

torch.float32

In [6]:
t22= torch.tensor([1,2,3,4])
t22

tensor([1, 2, 3, 4])

In [7]:
t22.dtype

torch.int64

In [8]:
#Matrix
t3= torch.tensor([[5.,6],
                  [7,8],
                  [9,10]])
t3


tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [9]:
t3.dtype

torch.float32

In [10]:
# 3-dimensional array
t4 = torch.tensor([
                   [[11,12,13],
                    [13,14,15]],
                   [[15,16,17],
                    [17.,14,15]]
])
t4


tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 14., 15.]]])

In [11]:
t4.dtype

torch.float32

In [12]:
t4.shape

torch.Size([2, 2, 3])

In [13]:
t4.size()

torch.Size([2, 2, 3])

In [14]:
#Matrix
t5 = torch.tensor([[5.,6,],
                   [7,8],
                   [9,12]])
t5

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 12.]])

In [15]:
# Create Tensors
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [16]:
# Arithmetic Operations
y = w  * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [17]:
# compute derivatives
y.backward()

In [18]:
# Display Gradients
print('dy/dx:', x.grad)
print('dy/dw:',w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [19]:
print('dw/db:', (1/(w.grad))*b.grad)

dw/db: tensor(0.3333)


# Tensor Functioins

In [20]:
# creating tensor with fixed value for every element
t6 = torch.full((3,2),1.+41)
t6

tensor([[42., 42.],
        [42., 42.],
        [42., 42.]])

In [21]:
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [22]:
# concatenate two tensors with compateible shapes
t7 = torch.cat((t3,t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [23]:
# compute the sin of each element
t8 = torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [24]:
# change the shape of a  tensor
t9 = t8.reshape(3,2,2)
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

# Tensor operations and gradients

In [25]:
# create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [26]:
# Arithmatic operatons
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [27]:
# Compute derivatives
y.backward()

In [28]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:',w.grad)
print('dy/db:',b.grad)


dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [29]:
x,w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

# Tensor Functions


In [30]:
# create a tensor with fixed value for every element
t66 = torch.full((3,2),33)
t66

tensor([[33, 33],
        [33, 33],
        [33, 33]])

In [31]:
# concatenate two tensors with compatible shapes
t77= torch.cat((t3,t66))
t77

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [33., 33.],
        [33., 33.],
        [33., 33.]])

# Interoperability with Numpy

In [32]:
import numpy as np

x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [33]:
# convert numpy array to torch tensor
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]])

In [38]:
x.dtype,y.dtype

(dtype('int64'), torch.int64)

In [39]:
z= y.numpy()
z

array([[1, 2],
       [3, 4]])

In [40]:
!pip install jovian --upgrade --quiet

     |████████████████████████████████| 71kB 5.0MB/s 


In [41]:
import jovian