In [3]:
import torch

In [4]:
t1= torch.tensor(4.)
t1

tensor(4.)

In [5]:
type(t1)

torch.Tensor

In [6]:
t1.dtype

torch.float32

In [7]:
t2 = torch.tensor([1,2,3,4.])
t2

tensor([1., 2., 3., 4.])

In [8]:
type(t2
     )

torch.Tensor

In [9]:
t2.dtype

torch.float32

In [10]:
# Matrix
t3= torch.tensor([[1.,2,3,4],[5,6,7,8],[9,8,7,4]])
t3

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.],
        [9., 8., 7., 4.]])

In [11]:
t3.dtype

torch.float32

In [12]:
t3.shape


torch.Size([3, 4])

In [13]:
t4 = torch.tensor([[1,2],[2.,4],[2,4]])
t4

tensor([[1., 2.],
        [2., 4.],
        [2., 4.]])

# Tensor operations and Gradients


---



---



In [20]:
# create tensors
x = torch.tensor(3., requires_grad=True)
w= torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x,w,b

(tensor(3., requires_grad=True),
 tensor(4., requires_grad=True),
 tensor(5., requires_grad=True))

In [21]:
# arithmetic operations
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [22]:
# compute derivatives
y.backward()

In [23]:
# Display gradients
print('dy/dx', x.grad)

dy/dx tensor(4.)


In [24]:
print('dy/dw',w.grad)

dy/dw tensor(3.)


In [25]:
print('dy/db',b.grad)

dy/db tensor(1.)


# Tensor Functions

---



---



In [27]:
t6 = torch.full((3,2),44)
t6

tensor([[44, 44],
        [44, 44],
        [44, 44]])

In [29]:
t7 = torch.cat((t6,t6))
t7

tensor([[44, 44],
        [44, 44],
        [44, 44],
        [44, 44],
        [44, 44],
        [44, 44]])

In [30]:
t8 = torch.sin(t7)

In [31]:
t8

tensor([[0.0177, 0.0177],
        [0.0177, 0.0177],
        [0.0177, 0.0177],
        [0.0177, 0.0177],
        [0.0177, 0.0177],
        [0.0177, 0.0177]])

In [32]:
t9 = torch.tan(t7)

In [33]:
t9

tensor([[0.0177, 0.0177],
        [0.0177, 0.0177],
        [0.0177, 0.0177],
        [0.0177, 0.0177],
        [0.0177, 0.0177],
        [0.0177, 0.0177]])

In [34]:
t99= t8.reshape(3,2,2)

In [35]:
t99

tensor([[[0.0177, 0.0177],
         [0.0177, 0.0177]],

        [[0.0177, 0.0177],
         [0.0177, 0.0177]],

        [[0.0177, 0.0177],
         [0.0177, 0.0177]]])

#Interoperability with Numpy

---



---



In [43]:
import numpy as np
x= np.array([[1,2.],[3,4]])
x

array([[1., 2.],
       [3., 4.]])

In [44]:
x.dtype

dtype('float64')

In [45]:
x.shape

(2, 2)

In [46]:
y = torch.from_numpy(x)

In [47]:
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [48]:
y.dtype

torch.float64

In [49]:
y.shape

torch.Size([2, 2])

In [50]:
z= y.numpy()
z

array([[1., 2.],
       [3., 4.]])

In [51]:
type(z)

numpy.ndarray